### ISSUE TITLE
Some character errors in my settings.xml 

### ISSUE THREAD

**Issue by sKulls-inc** [kyokusa/skin.Bello.Nero#3]
Hello,
I noticed that in my settings.xml some character errors are included.
What can I do to fix these errors?

[settings.zip](https://github.com/kyokusa/skin.Bello.Nero/files/3513455/settings.zip)

`<settings>
    <setting id="multicolor_theme" type="bool">false</setting>
    <setting id="skinshortcuts-widget-OnAirTVShows" type="bool">true</setting>
    <setting id="QuickNavRecentTVShowsButton" type="bool">false</setting>
    <setting id="EnableGlobalRSS" type="bool">false</setting>
    <setting id="EnableNextAiredNotifications" type="bool">false</setting>
    <setting id="skinshortcuts-widget-WeatherSubmenu" type="bool">false</setting>
    <setting id="AutoUpdateArt.Enabled" type="bool">false</setting>
    <setting id="BannersView" type="bool">true</setting>
    <setting id="3DWallViewMusic" type="bool">false</setting>
    <setting id="DisableVideoListView_PosterGlow" type="bool">false</setting>
    <setting id="Vis-MusicSlideshow" type="bool">false</setting>
    <setting id="QuickNavAddonsButton" type="bool">false</setting>
    <setting id="HideSystemTime" type="bool">false</setting>
    <setting id="Ã£Ã¿Ã®ÂµÃ®Â¹Ã®Â¹Ã¯Æ’_theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://skin/extras/backgrounds/chill zone/" type="bool">false</setting>
    <setting id="Ã£Ã¿Ã®ÂµÃ®Â¹Ã®Â¹Ã¯Æ’ Ã£Ã¿Ã®Â¹Ã¢ÂµÃ®Âµ_theme" type="bool">false</setting>
    <setting id="AutocompletionKBEnabled" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://skin/extras/backgrounds/" type="bool">true</setting>
    <setting id="furniture.clock" type="bool">false</setting>
    <setting id="Vis-Visualization" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/MovieandTv/" type="bool">true</setting>
    <setting id="skinshortcuts-background-Home_Movie_Fanart" type="bool">false</setting>
    <setting id="HideTVGuideFanart" type="bool">false</setting>
    <setting id="QuickNavUpdateVideoLibraryButton" type="bool">false</setting>
    <setting id="DisableListWallView_PosterGlow" type="bool">false</setting>
    <setting id="postersviewvideos2" type="bool">false</setting>
    <setting id="HideHomeNPVideoInfo" type="bool">false</setting>
    <setting id="QuickNavCleanVideoLibraryButton" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Comedy/" type="bool">true</setting>
    <setting id="QuickNavTVShowsButton" type="bool">false</setting>
    <setting id="Vis-Fanart" type="bool">false</setting>
    <setting id="EnableAddonsNotifications" type="bool">true</setting>
    <setting id="3dwallviewvideos" type="bool">false</setting>
    <setting id="SkinHelper.EnableDayNightThemes" type="bool">false</setting>
    <setting id="enablebgiconweathercond" type="bool">false</setting>
    <setting id="ÃŸÎµÎ¹Î¹Ïƒ ÃŸÎ¹ÂµÎµ_Theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-Home_Global_Fanart" type="bool">false</setting>
    <setting id="ClassicHomeMenu" type="bool">true</setting>
    <setting id="skinshortcuts-widget-CustomItems" type="bool">true</setting>
    <setting id="enablestudiolabelimages" type="bool">false</setting>
    <setting id="QuickNavSettingsButton" type="bool">false</setting>
    <setting id="NextAiredEnabled" type="bool">true</setting>
    <setting id="bannersviewvideos" type="bool">false</setting>
    <setting id="showtimeviewvideos" type="bool">false</setting>
    <setting id="galleryviewvideos" type="bool">false</setting>
    <setting id="HomeMenuAnimation" type="bool">false</setting>
    <setting id="HideBGVideo" type="bool">false</setting>
    <setting id="skinshortcuts-background-Home_TV_Fanart" type="bool">false</setting>
    <setting id="kioskmode" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/System/" type="bool">true</setting>
    <setting id="disablecontext:script.artwork.beef" type="bool">false</setting>
    <setting id="DisableWallView_PosterGlow" type="bool">false</setting>
    <setting id="HideHomeNPMusicInfo" type="bool">false</setting>
    <setting id="SkinHelper.ForcedViews.Enabled" type="bool">false</setting>
    <setting id="DisablePostersView2_PosterGlow" type="bool">false</setting>
    <setting id="DisableMusicListView_ThumbGlow" type="bool">false</setting>
    <setting id="enablecontext:script.artwork.beef.debug" type="bool">false</setting>
    <setting id="HideOSDDiffuseColors" type="bool">false</setting>
    <setting id="ShowSmallVideoThumbs" type="bool">false</setting>
    <setting id="SmartShortcuts.playlists" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="QuickNavFileManagerButton" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="skinshortcuts-widget-plugin://script.skin.helper.widgets/?action=favouriteslisting" type="bool">true</setting>
    <setting id="SkinHelper.EnableMusicArt" type="bool">false</setting>
    <setting id="ruby_theme" type="bool">false</setting>
    <setting id="ÃƒÂ£ÃƒÂ¿ÃƒÂ®Ã‚ÂµÃƒÂ®Ã‚Â¹ÃƒÂ®Ã‚Â¹ÃƒÂ¯Ã†â€™ ÃƒÂ®Ã‚Â·ÃƒÂ®Ã‚ÂµrÃƒÂ¯Ã†â€™_theme" type="bool">false</setting>
    <setting id="ShowDebugInfo" type="bool">false</setting>
    <setting id="QuickNavMoviesButton" type="bool">false</setting>
    <setting id="MusicInfoOSD" type="bool">false</setting>
    <setting id="DisableQuickNav" type="bool">false</setting>
    <setting id="QuickNavCleanMusicLibraryButton" type="bool">false</setting>
    <setting id="skinshortcuts-widget-InCinemasMovies" type="bool">true</setting>
    <setting id="ShowProgramInfo" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/XXX/" type="bool">true</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="QuickNavPartyModeButton" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/MovieandTv/" type="bool">true</setting>
    <setting id="plexbmc" type="bool">false</setting>
    <setting id="ãÿîµî¹î¹ïƒ î·îµrïƒ_theme" type="bool">false</setting>
    <setting id="SkinHelper.EnableExtraPoster" type="bool">false</setting>
    <setting id="skinshortcuts-widget-Settings" type="bool">true</setting>
    <setting id="ÃŸÎµÎ¹Î¹Ïƒ_Theme" type="bool">false</setting>
    <setting id="slideviewvideos" type="bool">false</setting>
    <setting id="Disable.WeatherClockDate" type="bool">false</setting>
    <setting id="Enable.CenteredMenu" type="bool">false</setting>
    <setting id="Vis-ArtistSlideshow" type="bool">false</setting>
    <setting id="netfilxviewvideos" type="bool">false</setting>
    <setting id="HideExtraInfo" type="bool">false</setting>
    <setting id="QuickNavSearchButton" type="bool">false</setting>
    <setting id="SlideViewMusic" type="bool">false</setting>
    <setting id="EnableWeatherAlertsNotifications" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Kids/" type="bool">true</setting>
    <setting id="ãÿîµî¹î¹ïƒ ãÿî¹âµîµ_theme" type="bool">false</setting>
    <setting id="QuickNavLiveTVButton" type="bool">false</setting>
    <setting id="sky_theme" type="bool">true</setting>
    <setting id="HideOSDScrollingTitles" type="bool">false</setting>
    <setting id="QuickNavRecentMoviesButton" type="bool">false</setting>
    <setting id="DisableAddonsListView_PosterGlow" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/" type="bool">false</setting>
    <setting id="SmartShortcuts.emby" type="bool">false</setting>
    <setting id="skinshortcuts-widget-AiringTodayTVShows" type="bool">true</setting>
    <setting id="skinshortcuts-widget-TrendingTVShows" type="bool">true</setting>
    <setting id="Disable3DWallMusicView_ThumbGlow" type="bool">false</setting>
    <setting id="QuickNavShutdownButton" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/" type="bool">false</setting>
    <setting id="AutoScroll" type="bool">false</setting>
    <setting id="Toggling" type="bool">false</setting>
    <setting id="TilesViewMusic" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="QuickNavVideosButton" type="bool">false</setting>
    <setting id="ShowLogoAsTtile" type="bool">false</setting>
    <setting id="DisablePostersView_PosterGlow" type="bool">false</setting>
    <setting id="SkinHelper.EnablePVRThumbs" type="bool">false</setting>
    <setting id="ÃŸÎµÎ¹Î¹Ïƒ Î·ÎµrÏƒ_Theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Adult/" type="bool">true</setting>
    <setting id="ÃƒÅ¸ÃŽÂµÃŽÂ¹ÃŽÂ¹ÃÆ’ ÃŽÂ·ÃŽÂµrÃÆ’_Theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-BackgroundWeather" type="bool">false</setting>
    <setting id="Vis-Animation" type="bool">false</setting>
    <setting id="ShowSmallAddonsThumbs" type="bool">false</setting>
    <setting id="Contexting" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Musik/" type="bool">false</setting>
    <setting id="BlackGlassMode" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Sports/" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Sports/" type="bool">true</setting>
    <setting id="BelloViewVideos2" type="bool">false</setting>
    <setting id="SkinHelper.EnableExtendedArt" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://skin/extras/backgrounds/photo_2018-01-30_15-52-57.jpg" type="bool">false</setting>
    <setting id="DisablePicturesListView_PosterGlow" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Music/" type="bool">true</setting>
    <setting id="furniture.topweather" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="ThumbnailsMusic" type="bool">false</setting>
    <setting id="ThumbnailsVideos" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Global/" type="bool">true</setting>
    <setting id="Ã£Ã¿Ã®ÂµÃ®Â¹Ã®Â¹Ã¯Æ’ Ã®Â·Ã®ÂµrÃ¯Æ’_theme" type="bool">false</setting>
    <setting id="skinshortcuts-widget-Addon" type="bool">true</setting>
    <setting id="SkinShortcuts-FullMenu" type="bool">true</setting>
    <setting id="HideBGFanart" type="bool">false</setting>
    <setting id="ThumbnailShowInfo" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://home/addons/resource.images.weatherfanart.multi/resources/" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/" type="bool">false</setting>
    <setting id="QuickNavRecentMusicButton" type="bool">false</setting>
    <setting id="postersviewvideos" type="bool">false</setting>
    <setting id="SkinHelper.EnableExtraFanart" type="bool">false</setting>
    <setting id="Disable.WeatherClock" type="bool">false</setting>
    <setting id="ÃƒÅ¸ÃŽÂµÃŽÂ¹ÃŽÂ¹ÃÆ’ ÃƒÅ¸ÃŽÂ¹Ã‚ÂµÃŽÂµ_Theme" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Kids/" type="bool">true</setting>
    <setting id="QuickNavMusicButton" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/" type="bool">false</setting>
    <setting id="wallviewvideos" type="bool">false</setting>
    <setting id="FlashingCinemaLights" type="bool">false</setting>
    <setting id="SkinHelper.EnableAnimatedPosters" type="bool">false</setting>
    <setting id="tilesviewvideos" type="bool">false</setting>
    <setting id="Enable.HomeTopbar" type="bool">false</setting>
    <setting id="EnableKioskMode" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="furniture.weather" type="bool">false</setting>
    <setting id="Enable.WeatherInMenu" type="bool">false</setting>
    <setting id="QuickNavUpdateIMDbRatingsButton" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="ÃƒÂ£ÃƒÂ¿ÃƒÂ®Ã‚ÂµÃƒÂ®Ã‚Â¹ÃƒÂ®Ã‚Â¹ÃƒÂ¯Ã†â€™_theme" type="bool">false</setting>
    <setting id="BelloViewMusic" type="bool">false</setting>
    <setting id="HomeMenuOverlay" type="bool">true</setting>
    <setting id="skinshortcuts-widget-Library" type="bool">true</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="enable.smartish.widgets" type="bool">true</setting>
    <setting id="SmartShortcuts.favorites" type="bool">false</setting>
    <setting id="ãÿîµî¹î¹ïƒ_theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Fitness/" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Wetter/" type="bool">true</setting>
    <setting id="HideWeather" type="bool">false</setting>
    <setting id="ShowSmallMusicAddonsThumbs" type="bool">false</setting>
    <setting id="listwallviewvideos" type="bool">false</setting>
    <setting id="BannersViewMusic" type="bool">false</setting>
    <setting id="SkinHelper.DisableScreenSaverOnFullScreenMusic" type="bool">false</setting>
    <setting id="skinshortcuts-background-C:\kodi-18_3-Leia-x64\portable_data\userdata\SkullsBuildWalls\Comedy\" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Mediathek/" type="bool">true</setting>
    <setting id="hidehometitleinfofanart" type="bool">false</setting>
    <setting id="furniture.header" type="bool">false</setting>
    <setting id="ShowSmallProgramsThumbs" type="bool">false</setting>
    <setting id="QuickNavSkinSettingsButton" type="bool">false</setting>
    <setting id="DownloadExtraArt" type="bool">true</setting>
    <setting id="QuickNavPicturesButton" type="bool">false</setting>
    <setting id="orange_theme" type="bool">false</setting>
    <setting id="EnableArtworkDownloader" type="bool">false</setting>
    <setting id="videowallviewvideos" type="bool">false</setting>
    <setting id="skinshortcuts-widget-SmartishTVChannels" type="bool">true</setting>
    <setting id="QuickNavFavouritesButton" type="bool">false</setting>
    <setting id="skinshortcuts-widget-Weather10DaysForecast" type="bool">true</setting>
    <setting id="green_theme" type="bool">false</setting>
    <setting id="BelloViewVideos" type="bool">false</setting>
    <setting id="skinshortcuts-widget-TVChannels" type="bool">true</setting>
    <setting id="fullscreenmusic" type="bool">false</setting>
    <setting id="AutoHideHomeWidgets" type="bool">true</setting>
    <setting id="skinshortcuts-widget-PopularTVShows" type="bool">true</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/MovieandTv/" type="bool">true</setting>
    <setting id="SmartShortcuts.plex" type="bool">false</setting>
    <setting id="ÃƒÅ¸ÃŽÂµÃŽÂ¹ÃŽÂ¹ÃÆ’_Theme" type="bool">false</setting>
    <setting id="skinshortcuts-background-special://userdata/SkullsBuildWalls/Comedy/" type="bool">true</setting>
    <setting id="SkinHelper.EnableWallBackgrounds" type="bool">false</setting>
    <setting id="Disable3DWallView_PosterGlow" type="bool">false</setting>
    <setting id="ShowSmallMusicThumbs" type="bool">false</setting>
    <setting id="QuickNavUpdateMusicLibraryButton" type="bool">false</setting>
    <setting id="GalleryViewMusic" type="bool">false</setting>
    <setting id="TMDB_API" type="string"></setting>
    <setting id="CustomItem.4.Path" type="string"></setting>
    <setting id="TileViewWideThumbMovies" type="string">1</setting>
    <setting id="QuickNavWidgetMoviesType" type="string">1</setting>
    <setting id="IMDBUpdate.label" type="string"></setting>
    <setting id="SkinHelper.AutoCloseVideoOSD" type="string"></setting>
    <setting id="CustomItem.8.Label" type="string"></setting>
    <setting id="colorlyricsselect" type="string"></setting>
    <setting id="QuickNavWidgetTVShowsType.label" type="string">Keine</setting>
    <setting id="CustomItem.10.Path" type="string"></setting>
    <setting id="SearchType" type="string"></setting>
    <setting id="CustomItem.5.Path" type="string"></setting>
    <setting id="ExtraArt.label" type="string"></setting>
    <setting id="LyricScript_Path" type="string">script.cu.lrclyrics</setting>
    <setting id="headertexttype" type="string">true</setting>
    <setting id="HashLib" type="string"></setting>
    <setting id="CustomItem.10.Thumb" type="string"></setting>
    <setting id="CustomItem.7.Path" type="string"></setting>
    <setting id="CustomItem.6.Path" type="string"></setting>
    <setting id="WeatherFanart.path" type="string"></setting>
    <setting id="screensaver.digitalclock.backgroundcolor.name" type="string"></setting>
    <setting id="TVDB_CFG" type="string"></setting>
    <setting id="screensaver.digitalclock.ampmcolor.name" type="string"></setting>
    <setting id="WeatherExtended" type="string">1</setting>
    <setting id="CustomItem.9.Label" type="string"></setting>
    <setting id="skinshortcuts-sharedmenu" type="string">true</setting>
    <setting id="DialogSeekBarStyle" type="string">1</setting>
    <setting id="RSSVideoFeedURL" type="string">Euronews</setting>
    <setting id="screensaver.digitalclock.ampmcolor" type="string"></setting>
    <setting id="screensaver.digitalclock.shadowcolor.name" type="string"></setting>
    <setting id="BelloViewThumbs" type="string">1</setting>
    <setting id="CustomItem.4.Label" type="string"></setting>
    <setting id="FullScreenMusicStyle" type="string">1</setting>
    <setting id="screensaver.digitalclock.minutecolor" type="string"></setting>
    <setting id="CustomItem.7.Thumb" type="string"></setting>
    <setting id="SkinHelper.RandomFanartDelay" type="string">10</setting>
    <setting id="CustomItem.1.Label" type="string"></setting>
    <setting id="GalleryViewWideThumbMovies" type="string">1</setting>
    <setting id="MusicArtPath" type="string"></setting>
    <setting id="osd.cdartselect" type="string"></setting>
    <setting id="HomeLayout" type="string"></setting>
    <setting id="SkinHelper.AutoCloseMusicOSD" type="string"></setting>
    <setting id="skinshortcuts-widget-5" type="string">Addon</setting>
    <setting id="weathericons.name" type="string"></setting>
    <setting id="osd.discartselect" type="string"></setting>
    <setting id="IMDBUpdate" type="string"></setting>
    <setting id="QuickNavWidgetMusicType.label" type="string">Keine</setting>
    <setting id="skinshortcuts-widget-6" type="string">Addon</setting>
    <setting id="screensaver.digitalclock.coloncolor" type="string"></setting>
    <setting id="QuickNavWidgetType" type="string">1</setting>
    <setting id="screensaver.digitalclock.datecolor.name" type="string"></setting>
    <setting id="BG.GlobalColor" type="string"></setting>
    <setting id="ListViewWideThumbMovies" type="string">1</setting>
    <setting id="WindowColorMain" type="string">ff000000</setting>
    <setting id="QuickNavWidgetTVShowsType" type="string">1</setting>
    <setting id="screensaver.digitalclock.coloncolor.name" type="string"></setting>
    <setting id="screensaver.digitalclock.hourcolor" type="string"></setting>
    <setting id="SkinHelper.ColorTheme.Day.time" type="string"></setting>
    <setting id="skinshortcuts-widget-7" type="string">Addon</setting>
    <setting id="CustomItem.1.Path" type="string"></setting>
    <setting id="WindowColorThemed" type="string">ff33ff00</setting>
    <setting id="weathericons.multi" type="string"></setting>
    <setting id="CustomItem.10.Label" type="string"></setting>
    <setting id="CustomItem.4.Thumb" type="string"></setting>
    <setting id="PreviewThumb" type="string">1</setting>
    <setting id="screensaver.digitalclock.minutecolor.name" type="string"></setting>
    <setting id="CustomItem.6.Thumb" type="string"></setting>
    <setting id="CustomItem.3.Label" type="string"></setting>
    <setting id="screensaver.digitalclock.datecolor" type="string"></setting>
    <setting id="weathericons.path" type="string"></setting>
    <setting id="CustomItem.5.Thumb" type="string"></setting>
    <setting id="TileViewWideThumbTVShows" type="string">1</setting>
    <setting id="WeatherFanart.name" type="string"></setting>
    <setting id="CustomItem.7.Label" type="string"></setting>
    <setting id="CustomItem.8.Thumb" type="string"></setting>
    <setting id="CustomItem.1.Thumb" type="string"></setting>
    <setting id="screensaver.digitalclock.hourcolor.name" type="string"></setting>
    <setting id="CustomItem.6.Label" type="string"></setting>
    <setting id="RSSVideoFeedType" type="string">User</setting>
    <setting id="SkinHelper.StudioLogos.Path" type="string"></setting>
    <setting id="GalleryViewWideThumbTVShows" type="string">1</setting>
    <setting id="screensaver.digitalclock.iconcolor" type="string"></setting>
    <setting id="TrailersAddon_Path" type="string"></setting>
    <setting id="CustomItem.2.Label" type="string"></setting>
    <setting id="RSSVideoFeedURL.label" type="string">Euronews (Default)</setting>
    <setting id="CustomItem.9.Thumb" type="string"></setting>
    <setting id="skinshortcuts-widget-3" type="string">TVChannels</setting>
    <setting id="ExtraArt" type="string"></setting>
    <setting id="screensaver.digitalclock.iconcolor.name" type="string"></setting>
    <setting id="SkinHelper.ColorTheme.Night.time" type="string"></setting>
    <setting id="WeatherCheck" type="string"></setting>
    <setting id="ListViewWideThumbTVShows" type="string">1</setting>
    <setting id="CustomItem.5.Label" type="string"></setting>
    <setting id="screensaver.digitalclock.shadowcolor" type="string"></setting>
    <setting id="QuickNavWidgetMoviesType.label" type="string">Keine</setting>
    <setting id="CustomItem.9.Path" type="string"></setting>
    <setting id="QuickNavWidgetMusicType" type="string">1</setting>
    <setting id="CustomItem.3.Path" type="string"></setting>
    <setting id="osd.artselect" type="string"></setting>
    <setting id="screensaver.digitalclock.backgroundcolor" type="string"></setting>
    <setting id="CustomItem.3.Thumb" type="string"></setting>
    <setting id="QuickNavWidgetType.label" type="string">Schnellnavigation</setting>
    <setting id="Textures.GlobalColor" type="string"></setting>
    <setting id="skinshortcuts-widget-1" type="string">Addon</setting>
    <setting id="Text.GlobalColor" type="string">FFc90533</setting>
    <setting id="screensaver.digitalclock.informationcolor" type="string"></setting>
    <setting id="CustomItem.2.Thumb" type="string"></setting>
    <setting id="screensaver.digitalclock.informationcolor.name" type="string"></setting>
    <setting id="SkinHelper.ShowInfoAtPlaybackStart" type="string"></setting>
    <setting id="skinshortcuts-widget-2" type="string">PopularTVShows</setting>
    <setting id="CustomItem.8.Path" type="string"></setting>
    <setting id="CustomItem.2.Path" type="string"></setting>
    <setting id="skinshortcuts-widget-4" type="string">Addon</setting>
    <setting id="FullScreenVideoStyle" type="string">1</setting>
    <setting id="headerimagetype" type="string">true</setting>
    <setting id="SearchType.label" type="string"></setting>
</settings>
`

I hope anyone can help me :) Thanks in advance :)#

Cheers

Skully

**Comment by kyokusa** [comment]
Which version are you using of BelloNero and Kodi.
If you have installed BelloNero.zip according to the procedure you should have no problem in the settings.xml file.
Try making a backup of the settings.xml file then delete it from the addon_data directory and re-launch Kodi resets everything and it will fall into place.
NB make sure you have beautiful Nero 7.0.3a and kodi 18.3 2019.06.21.
Greetings

**Comment by sKulls-inc** [comment]
I´m usind Kodi Leia 18.3 Git: 20190619-89472b7d69  with Bello Nero 7.0.3.a :)

Cheers 

Skull

**Comment by sKulls-inc** [comment]
Ok... I did it, what you say :)
I deleted the settings.xml from the User/Addon_Data .
I run Kodi and Bello creates an new one :)
But the same error :/ ... ii try now to deinstall an install Bello completely new.
With a little bit luck .. it works :)

Cheers

Skull

[settings.zip](https://github.com/kyokusa/skin.Bello.Nero/files/3514024/settings.zip)
